"""household link_code

Revision ID: 8adb3bc68dc9
Revises: c40df9af5b4b
Create Date: 2026-08-16 11:43:07.643795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8adb3bc68dc9'
down_revision: Union[str, Sequence[str], None] = 'c40df9af5b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('households', sa.Column('link_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_households_link_code'), 'households', ['link_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_households_link_code'), table_name='households')
    op.drop_column('households', 'link_code')
    # ### end Alembic commands ###
