"""household channel and lead_hours preferences

Revision ID: 99a530f02f99
Revises: eb1d235c7589
Create Date: 2026-08-15 21:19:13.276438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99a530f02f99'
down_revision: Union[str, Sequence[str], None] = 'eb1d235c7589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('households', sa.Column('preferred_channel', sa.String(), nullable=True))
    op.add_column('households', sa.Column('lead_hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('households', 'lead_hours')
    op.drop_column('households', 'preferred_channel')
    # ### end Alembic commands ###
