"""household owner_user_id

Revision ID: c40df9af5b4b
Revises: 99a530f02f99
Create Date: 2026-08-15 21:23:54.888367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c40df9af5b4b'
down_revision: Union[str, Sequence[str], None] = '99a530f02f99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('households', sa.Column('owner_user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_households_owner_user_id'), 'households', ['owner_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_households_owner_user_id'), table_name='households')
    op.drop_column('households', 'owner_user_id')
    # ### end Alembic commands ###
