"""household city and state

Revision ID: eb1d235c7589
Revises: eba8c57e135e
Create Date: 2026-08-15 20:51:21.763905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb1d235c7589'
down_revision: Union[str, Sequence[str], None] = 'eba8c57e135e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('households', sa.Column('city', sa.String(), nullable=True))
    op.add_column('households', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('households', 'state')
    op.drop_column('households', 'city')
    # ### end Alembic commands ###
