"""baseline schema

Revision ID: eba8c57e135e
Revises: 
Create Date: 2026-08-14 02:38:27.738430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eba8c57e135e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cook_name', sa.String(), nullable=False),
    sa.Column('cook_phone', sa.String(), nullable=False),
    sa.Column('send_time', sa.String(), nullable=True),
    sa.Column('diet_type', sa.String(), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('disliked_ingredients', sa.JSON(), nullable=True),
    sa.Column('preferred_cuisines', sa.JSON(), nullable=True),
    sa.Column('spice_level', sa.String(), nullable=True),
    sa.Column('family_size', sa.Integer(), nullable=True),
    sa.Column('kids_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('caspian_connection_id', sa.String(), nullable=True),
    sa.Column('caspian_conversation_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cook_phone')
    )
    op.create_table('recipes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('cuisine_style', sa.String(), nullable=True),
    sa.Column('meal_types', sa.JSON(), nullable=True),
    sa.Column('diet', sa.String(), nullable=True),
    sa.Column('spice_level', sa.String(), nullable=True),
    sa.Column('prep_time_min', sa.Integer(), nullable=True),
    sa.Column('main_ingredient_category', sa.String(), nullable=True),
    sa.Column('season_tags', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region_cuisine_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('cuisine_style', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_region_cuisine_map_state'), 'region_cuisine_map', ['state'], unique=False)
    op.create_table('meal_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_plan_id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_slot', sa.String(), nullable=False),
    sa.Column('dish_recipe_ids', sa.JSON(), nullable=True),
    sa.Column('portion_servings', sa.Float(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('meal_plan_item_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed_intent', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['meal_plan_item_id'], ['meal_plan_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_table('meal_plan_items')
    op.drop_table('meal_plans')
    op.drop_index(op.f('ix_region_cuisine_map_state'), table_name='region_cuisine_map')
    op.drop_table('region_cuisine_map')
    op.drop_table('recipes')
    op.drop_table('households')
    # ### end Alembic commands ###
